const test = require("node:test");
const assert = require("node:assert/strict");
const { Client } = require("pg");

if (process.env.TEST_DATABASE_URL && !process.env.DATABASE_URL) {
  process.env.DATABASE_URL = process.env.TEST_DATABASE_URL;
}

const { pool } = require("../src/db/db");
const followUpRepo = require("../src/db/followUpRepo");

// This verifies actual SQL INSERT ... SELECT parent validation, not just SQL
// fragments mocked by unit tests. Never connect to production here.
test("PostgreSQL validates social media companion parents before insertion", {
  skip: !process.env.TEST_DATABASE_URL,
}, async () => {
  const client = new Client({ connectionString: process.env.TEST_DATABASE_URL, ssl: false });
  const schema = "fu_social_parent_" + process.pid + "_" + Date.now();
  const originalQuery = pool.query;
  await client.connect();
  try {
    await client.query("CREATE SCHEMA " + schema);
    await client.query("SET search_path TO " + schema);
    await client.query(`
      CREATE TABLE messages (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        contact_id INTEGER NOT NULL,
        role TEXT NOT NULL,
        content TEXT,
        whatsapp_message_id TEXT,
        sent_by_username TEXT,
        media_url TEXT,
        media_key TEXT,
        media_mime_type TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        delivery_status TEXT,
        delivery_error TEXT,
        is_automated_follow_up BOOLEAN NOT NULL DEFAULT false,
        automated_follow_up_step INTEGER NOT NULL DEFAULT 1,
        automated_follow_up_target_service TEXT,
        automated_follow_up_targeting_recorded BOOLEAN NOT NULL DEFAULT false,
        automated_follow_up_message_mode TEXT,
        automated_follow_up_for_message_id INTEGER,
        automated_follow_up_parent_message_id INTEGER REFERENCES messages(id) ON DELETE SET NULL
      );
      INSERT INTO messages (id, contact_id, role, content, is_automated_follow_up,
        automated_follow_up_step, automated_follow_up_for_message_id) VALUES
        (100,7,'assistant','Follow-up 3 text',true,3,90),
        (101,8,'assistant','Other contact follow-up',true,2,90),
        (102,7,'assistant','Manual message',false,1,NULL),
        (103,7,'assistant','Unanchored automation',true,1,NULL),
        (104,7,'assistant','Pricing reminder',true,4,NULL);
    `);
    // Only this isolated session is redirected. Restore the global pool even
    // if any assertion or SQL query throws.
    pool.query = (sql, params) => client.query(sql, params);

    const image = await followUpRepo.saveSocialImageCompanion({
      contactId: 7,
      parentMessageId: 100,
      imageUrl: "https://example.test/pelvis.jpg",
    });
    const video = await followUpRepo.saveSocialVideoCompanion({
      contactId: 7,
      parentMessageId: 100,
      mediaKey: "followups/testimonial.mp4",
      mediaMimeType: "video/mp4",
    });
    assert.ok(image?.id);
    assert.ok(video?.id);
    assert.notEqual(image.id, video.id);
    assert.equal(image.media_url, "https://example.test/pelvis.jpg");
    assert.equal(video.media_mime_type, "video/mp4");
    assert.equal(video.has_media_attachment, true);
    for (const id of [image.id, video.id]) {
      const saved = await client.query(
        "SELECT contact_id, automated_follow_up_parent_message_id, automated_follow_up_for_message_id, automated_follow_up_step FROM messages WHERE id = $1", [id],
      );
      assert.equal(saved.rows[0].contact_id, 7);
      assert.equal(saved.rows[0].automated_follow_up_parent_message_id, 100);
      assert.equal(saved.rows[0].automated_follow_up_for_message_id, null,
        "companion must not affect sequence or idempotency");
      assert.equal(saved.rows[0].automated_follow_up_step, 1);
    }

    for (const parentMessageId of [999, 101, 102, 103, 104]) {
      const badImage = await followUpRepo.saveSocialImageCompanion({
        contactId: 7, parentMessageId, imageUrl: "https://example.test/not-sent.jpg",
      });
      const badVideo = await followUpRepo.saveSocialVideoCompanion({
        contactId: 7, parentMessageId, mediaKey: "followups/not-sent.mp4",
      });
      assert.equal(badImage, null, "image should reject invalid parent " + parentMessageId);
      assert.equal(badVideo, null, "video should reject invalid parent " + parentMessageId);
    }
    const count = await client.query(
      "SELECT count(*)::integer AS n FROM messages WHERE automated_follow_up_parent_message_id IS NOT NULL",
    );
    assert.equal(count.rows[0].n, 2, "invalid parents must create no companion rows");
  } finally {
    pool.query = originalQuery;
    try {
      await client.query("SET search_path TO public");
      await client.query("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
    } finally {
      await client.end();
    }
  }
});
