const PROFILE_UI = {
  aesthetic_clinic: {
    businessNoun: "clinic",
    businessNameLabel: "Clinic name",
    businessAndAiLabel: "Clinic & AI",
    locationsLabel: "Branches",
    locationLabel: "Branch",
    locationSingular: "branch",
    locationPlural: "branches",
    leadLocationLabel: "Branch",
    leadLocationHint: "Only branches that currently exist in Settings can be newly selected.",
    servicesLabel: "Treatments",
    serviceSingular: "treatment",
    servicePlural: "treatments",
    serviceInterestLabel: "Treatment interest",
    serviceInterestFallback: "Treatment not selected",
    insightsInterestLabel: "Treatment / Interest",
    preferredLocationLabel: "Preferred Branch",
    conversionLabel: "Appointment",
    conversionStatusLabel: "Appointment status",
    conversionDateTimeLabel: "Appointment date and time",
    conversionCountSingular: "appointment",
    conversionCountPlural: "appointments",
    staffLocationLabel: "Sales branch",
    noFixedLocationLabel: "No fixed branch",
    conversionStageKeys: {
      set: "appointment_set",
      visited: "visited",
    },
    qualificationView: null,
    conversionStatusOptions: [
      ["none", "No appointment"],
      ["set", "Appointment set"],
      ["reschedule", "Needs reschedule"],
      ["cancelled", "Cancelled"],
      ["visited", "Visited clinic"],
    ],
  },
  home_renovation: {
    businessNoun: "business",
    businessNameLabel: "Business name",
    businessAndAiLabel: "Business & AI",
    locationsLabel: "Locations",
    locationLabel: "Location",
    locationSingular: "location",
    locationPlural: "locations",
    leadLocationLabel: "Sales location",
    leadLocationHint: "Business or sales location only. The customer's project location appears in Project qualification.",
    servicesLabel: "Renovation Services",
    serviceSingular: "service",
    servicePlural: "services",
    serviceInterestLabel: "Service / project interest",
    serviceInterestFallback: "Service not selected",
    insightsInterestLabel: "Service / Project Interest",
    preferredLocationLabel: "Preferred Location",
    conversionLabel: "Next step",
    conversionStatusLabel: "Next-step status",
    conversionDateTimeLabel: "Next-step date and time",
    conversionCountSingular: "next step",
    conversionCountPlural: "next steps",
    staffLocationLabel: "Sales location",
    noFixedLocationLabel: "No fixed location",
    conversionStageKeys: {},
    qualificationView: {
      title: "Project qualification",
      description: "Latest project details captured from the conversation, alongside the current CRM status.",
      fields: [
        { key: "serviceInterest", label: "Service / project interest", source: "lead", path: "treatment_interest" },
        { key: "projectLocation", label: "Project location", source: "activity", path: "projectLocation" },
        { key: "projectSummary", label: "Project summary", source: "activity", path: "projectSummary" },
        { key: "nextStep", label: "Requested next step", source: "activity", path: "nextStep", format: "nextStep", snapshot: true },
        { key: "siteVisitTiming", label: "Preferred site-visit timing", source: "activity", path: "appointmentPreference", snapshot: true },
        { key: "estimatedValue", label: "Estimated value", source: "lead", path: "estimated_value", format: "money" },
        { key: "temperature", label: "Lead temperature", source: "lead", path: "temperature", format: "title" },
        { key: "owner", label: "Lead owner", source: "lead", path: "owner_username" },
        { key: "nextFollowUp", label: "Next follow-up", source: "lead", path: "next_follow_up_at", format: "dateTime" },
        { key: "source", label: "Source", source: "lead", path: "source" },
      ],
    },
    conversionStatusOptions: [
      ["none", "No next step"],
      ["set", "Next step set"],
      ["reschedule", "Needs reschedule"],
      ["cancelled", "Cancelled"],
      ["visited", "Visited / completed"],
    ],
  },
  generic: {
    businessNoun: "business",
    businessNameLabel: "Business name",
    businessAndAiLabel: "Business & AI",
    locationsLabel: "Locations",
    locationLabel: "Location",
    locationSingular: "location",
    locationPlural: "locations",
    leadLocationLabel: "Sales location",
    leadLocationHint: "Business or sales location assigned to this lead.",
    servicesLabel: "Services",
    serviceSingular: "service",
    servicePlural: "services",
    serviceInterestLabel: "Service interest",
    serviceInterestFallback: "Service not selected",
    insightsInterestLabel: "Service / Interest",
    preferredLocationLabel: "Preferred Location",
    conversionLabel: "Next step",
    conversionStatusLabel: "Next-step status",
    conversionDateTimeLabel: "Next-step date and time",
    conversionCountSingular: "next step",
    conversionCountPlural: "next steps",
    staffLocationLabel: "Sales location",
    noFixedLocationLabel: "No fixed location",
    conversionStageKeys: {},
    qualificationView: null,
    conversionStatusOptions: [
      ["none", "No next step"],
      ["set", "Next step set"],
      ["reschedule", "Needs reschedule"],
      ["cancelled", "Cancelled"],
      ["visited", "Visited / completed"],
    ],
  },
};

const DEFAULT_PROFILE = PROFILE_UI.generic;

export function getBusinessTerminology(config = {}) {
  const businessType = String(config?.businessType || "generic").trim();
  const profile = PROFILE_UI[businessType] || DEFAULT_PROFILE;
  const configured = config?.terminology || {};

  return {
    businessType,
    ...profile,
    customerSingular: String(configured.customerSingular || "customer").trim() || "customer",
    customerPlural: String(configured.customerPlural || "customers").trim() || "customers",
  };
}

export function getSettingsTabs(config = {}) {
  const ui = getBusinessTerminology(config);
  return [
    { id: "general", label: "General" },
    { id: "branches", label: ui.locationsLabel },
    { id: "hours", label: "Hours & Contact" },
    { id: "services", label: ui.servicesLabel },
    { id: "aliases", label: "Service Terms" },
    { id: "faqs", label: "FAQs" },
    { id: "promotions", label: "Promotions" },
    { id: "aiBehavior", label: "AI Behavior" },
    { id: "escalation", label: "Handoff & Rules" },
  ];
}
